<?php
namespace WorkLogger\Fakers;

class ProjectFaker extends \Faker\Provider\Base
{
    public function projectName()
    {
        // http://messybeast.com/breeds-a.htm
        $choices = [
            'Abyssinian',
            'Accicat',
            'Aegean',
            'African Shorthair',
            'Alaskan Snow',
            'Albino Siamese',
            'Algerian',
            'Allergen-Free',
            'Alpaca',
            'Alpine Lynx',
            'Altai',
            'American Blue',
            'American Bobtail',
            'American Curl',
            'American Forest ',
            'American Keuda',
            'American Longhair',
            'American Lynx',
            'American Mystery ',
            'American Polydactyl',
            'American Ringtail',
            'American Shag',
            'American Shorthair',
            'American Snughead',
            'American Wirehair',
            'Anatolian',
            'Ankhara',
            'Anglesey Bobtail',
            'Angola',
            'Annamese',
            'Antipodean',
            'Aphrodite\'s Giant ',
            'Appaloosa',
            'Asian Longhair ',
            'Asian Miniature',
            'Asian Shorthair',
            'Australian',
            'Australian Curl',
            'Australian Mist',
            'Australian Tiffanie',
            'Authentic',
            'Auvergne',
            'Aztec',
            'Azul Cubano',
            'Baby Doll',
            'Bagral',
            'Bahraini Dilmun',
            'Balinese',
            'Bambino',
            'BamBob',
            'Bangkok',
            'Benedictine',
            'Bengal',
            'Berkshire Brown',
            'Birchilla',
            'Birman',
            'Black Bengal',
            'Black Somali',
            'Blonde Havana',
            'Blue Siamese',
            'Blynx',
            'Bohemian Rex',
            'Bombay',
            'Bondanese',
            'Bonx',
            'Bramble',
            'Brazilian Shorthair',
            'Brimali',
            'Bristol',
            'Britanica',
            'British Shorthair',
            'British Tick',
            'Brooklyn Wooley',
            'Buckfast Blue',
            'Bunny',
            'Burmalayan',
            'Butterfly Rex',
        ];

        $key = array_rand($choices);
        return $choices[$key];
    }
}
