# CodeBuildでの実行時のイメージは公式イメージの「aws/codebuild/standard:2.0」を想定
version: 0.2

#env:
  #variables:
    # key: "value"
    # key: "value"
  #parameter-store:
    # key: "value"
    # key: "value"

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region=us-west-2)
      - REPOSITORY_URI="563848776164.dkr.ecr.us-west-2.amazonaws.com/work-logger-app"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)

  build:
    commands:
      - docker build -f docker/app/Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - |
        cat > task-definition.json <<EOT
        [{
          "name": "app",
          "imageUri": "${REPOSITORY_URI}:${IMAGE_TAG}"
        }]
        EOT

artifacts:
  files:
    - task-definition.json
