version: "3.5"
services:
  web:
    build:
      context: "."
    ports:
      - "80:80"
    volumes:
      - "./data/log:/var/log"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "worklogger"
      MYSQL_USER: "worklogger"
      MYSQL_PASSWORD: "testtest"
      MYSQL_ROOT_PASSWORD: "testtest"
    volumes:
      - "./data/mysql:/var/lib/mysql"
