version: "3.5"
services:
  app:
    image: "563848776164.dkr.ecr.us-west-2.amazonaws.com/work-logger-app:latest"
    build:
      target: "app"
      context: "."
    environment:
      USE_TEST_DB: "true"
    ports:
      - "9000:9000"
    volumes:
      - ".:/work-logger"
    depends_on:
      - db

  web:
    image: "563848776164.dkr.ecr.us-west-2.amazonaws.com/work-logger-web:latest"
    build:
      target: "web"
      context: "."
    environment:
      APP_HOST: app
    ports:
      - "18000:80"
    volumes:
      - ".:/work-logger"
    depends_on:
      - app

  worker:
    image: "563848776164.dkr.ecr.us-west-2.amazonaws.com/work-logger-app:latest"
    build:
      target: "app"
      context: "."
    command:
      [
        "/usr/local/bin/php",
        "/work-logger/artisan",
        "queue:listen",
        "--timeout=0",
      ]
    environment:
      APP_HOST: app
    volumes:
      - ".:/work-logger"
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    expose:
      - "3306"
    ports:
      - "18001:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "/var/lib/mysql"
      - "./docker/db:/etc/mysql/my.conf.d"
