version: "3.5"
services:
  # AWS CodeBuild 上で自動テストを実行するコンテナ用のサービス。
  code_build:
    build:
      context: "."
      dockerfile: docker/code_build/Dockerfile
      args:
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
        NO_PROXY: ""
    volumes:
    - ".:/src" # AWS CodeBuildではランダムな名前でマウントされるため注意

  # 上記以外のイメージを作成する場合、以下に追加してください。
  # Dockerfileはdockerフォルダ配下に作成してください。
