version: "3.5"
services:
  web:
    image: "563848776164.dkr.ecr.us-west-2.amazonaws.com/work-logger-web:latest"
    build:
      context: "."
    env_file:
      - .env
    ports:
      - "18000:80"
    volumes:
      - "./data/log:/var/log"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./docker/db:/etc/mysql/my.conf.d"
