
- name: MySQLがインストール済であること
  stat: path=/usr/sbin/mysqld
  register: mysql_stat
  changed_when: not mysql_stat.stat.exists

- name: mariadb-libsは存在しないこと
  yum:
    name:
    - mariadb-libs
    state: removed

- name: MySQLのインストール
  yum:
    name:
    - "https://downloads.mysql.com/archives/get/file/mysql-community-client-{{ mysql_version_major }}.{{ mysql_version_minor }}-1.el7.x86_64.rpm"
    - "https://downloads.mysql.com/archives/get/file/mysql-community-common-{{ mysql_version_major }}.{{ mysql_version_minor }}-1.el7.x86_64.rpm"
    - "https://downloads.mysql.com/archives/get/file/mysql-community-libs-{{ mysql_version_major }}.{{ mysql_version_minor }}-1.el7.x86_64.rpm"
    - "https://downloads.mysql.com/archives/get/file/mysql-community-server-{{ mysql_version_major }}.{{ mysql_version_minor }}-1.el7.x86_64.rpm"
    - "https://downloads.mysql.com/archives/get/file/mysql-community-devel-{{ mysql_version_major }}.{{ mysql_version_minor }}-1.el7.x86_64.rpm"
  when: not mysql_stat.stat.exists

- name: Mysql-pythonがインストールされていること
  pip:
    name: MySQL-python  #Ansible経由でMySQLを操作する場合に必要

- name: my.cnfが存在すること
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0664
  notify: restart_mysql

- name: MySQLログ用ディレクトリが存在すること
  file:
    path: /var/log/mysql
    owner: mysql
    group: mysql
    mode: 0755
    state: directory

- name: データディレクトリが初期化済であること
  stat: path=/var/lib/mysql_initialized
  register: mysql_initialized_stat
  changed_when: not mysql_initialized_stat.stat.exists

- name: データディレクトリの初期化
  shell: rm -rf /var/lib/mysql && mysqld --initialize-insecure --user=mysql
  when: not mysql_initialized_stat.stat.exists

- name: データディレクトリ初期化済の記録
  file:
    path: /var/lib/mysql_initialized
    state: touch
  when: not mysql_initialized_stat.stat.exists

- name: MySQLサービスが自動起動すること
  systemd:
    name: mysqld.service
    enabled: true
    state: started

- name: MySQLのlogrotate設定が存在すること
  template:
    src: ../templates/logrotate.d/mysql.j2
    dest: /etc/logrotate.d/mysql
    owner: root
    group: root
    mode: 0644

- name: Ansible用MySQL rootユーザー設定ファイルが存在すること
  template:
    src: ../templates/.my.cnf_for_root.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: 開発用DBの作成
  mysql_db: db={{ db_name }} state=present encoding=utf8mb4

- name: TEST用DBの作成
  mysql_db: db={{ test_db_name }} state=present encoding=utf8mb4
  when: not (test_db_name == '')

- name: MySQL開発DBアカウントの作成
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    host: "{{ item }}"
    priv: "*.*:ALL"
    append_privs: yes
    state: present
  with_items:
  - "127.0.0.1"
  - "localhost"
  - "192.168.%"
  - "10.0.%"
