
- name: tblsがインストールされていること
  stat: path=/usr/local/bin/tbls
  register: tbls_stat
  changed_when: not tbls_stat.stat.exists

- name: tblsのダウンロード
  get_url:
    url: https://github.com/k1LoW/tbls/releases/download/v1.14.0/tbls_v1.14.0_linux_amd64.tar.gz
    dest: /usr/local/src/tbls.tar.gz
    mode: '0644'
  when: not tbls_stat.stat.exists

- name: tblsのインストール
  unarchive:
    src: /usr/local/src/tbls.tar.gz
    dest: /usr/local/bin
  when: not tbls_stat.stat.exists

- name: tblsのtarballが削除されていること
  file:
    path: /usr/local/src/tbls.tar.gz
    state: absent
  when: not tbls_stat.stat.exists

- name: graphviz がインストールされていること
  yum:
    name:
      - graphviz

- name: pandocがインストールされていること
  yum:
    name: pandoc

