# ------------------------------------------------------
# nginx
nginx_version_major: 1
nginx_version_minor: 12
nginx_version_micro: 2

# ------------------------------------------------------
# PHP
php_version_major: 7
php_version_minor: 2
php_version_micro: 11

# ------------------------------------------------------
# MySQL
mysql_version_major: 5.7
mysql_version_minor: 23


# ------------------------------------------------------
# libXL
libxl_license_user: "Tetsuya Miyahara"
libxl_license_key: "linux-e1d11c7a9da8a617070d24334bo3j0n6"
