- name: Selinuxは無効化されていること
  selinux: state=disabled

- name: 開発環境ではiptables(firewalld)は無効化されていること
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: stage == 'development'

- name: 日本語のロケールを設定(1)
  shell: localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
  when: ansible_env.LANG != 'ja_JP.UTF-8'

- name: 日本語のロケールを設定(2)
  shell: localectl set-locale LANG=ja_JP.utf8
  when: ansible_env.LANG != 'ja_JP.UTF-8'

- name: タイムゾーンが日本であること
  timezone:
    name: Asia/Tokyo

- name: EPELリポジトリがインストールされていること
  yum: name=epel-release

- name: 基本パッケージがインストール済であること
  yum:
    name:
    - less
    - vim
    - curl
    - git
    - python
    - python-pip
    - python-devel
    - jq
    - lsof
    - tmux

- name: "[ローカル用]aws-cliがインストールされていること"
  pip:
    name:
      - awscli
  when: env == 'vagrant'

- name: "[ローカル用]VM起動時のlogrotate実行サービスが定義されていること"
  template:
    src: ../templates/etc/systemd/system/dev-logrotate.service.j2
    dest: /etc/systemd/system/dev-logrotate.service
    owner: root
    group: root
    mode: 0644
  when: env == 'vagrant'

- name: "[ローカル用]VM起動時のlogrotate実行サービスが定義されていること"
  systemd:
    name: dev-logrotate
    daemon_reload: yes
    enabled: yes
  when: env == 'vagrant'

