- name: Ensure nginx exists
  yum:
    name:
    - nginx


- name: nginxのルート設定ファイルが存在すること
  template:
    src: ../templates/etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0664
  notify: restart_nginx

- name: nginxの設定ファイルが存在すること
  template:
    src: ../templates/etc/nginx/conf.d/web.conf.j2
    dest: /etc/nginx/conf.d/web.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_nginx

- name: nginxログ用ディレクトリが存在すること
  file:
    path: /var/log/nginx
    owner: nginx
    group: nginx
    mode: 0755
    state: directory

- name: nginx用logrotate設定が存在すること
  template:
    src: ../templates/etc/logrotate.d/nginx.j2
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644

- name: nginxサービスが自動起動すること
  systemd:
    name: nginx.service
    enabled: true
    state: started
