- name: Ensure nginx exists
  yum:
    name:
    - nginx


- name: Ensure nginx global config up to date
  template:
    src: ../templates/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0664
  notify: restart_nginx

- name: Ensure nginx site config up to date
  template:
    src: ../templates/nginx/conf.d/web.conf.j2
    dest: /etc/nginx/conf.d/web.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_nginx

- name: nginxログ用ディレクトリが存在すること
  file:
    path: /var/log/nginx
    owner: nginx
    group: nginx
    mode: 0775
    state: directory

- name: nginxサービスが自動起動すること
  systemd:
    name: nginx.service
    enabled: true
    state: started
