- name: Remiリポジトリが存在すること
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present


- name: PHPとLaravel関連モジュールがインストールさてていること
  yum:
    enablerepo: "remi,remi-php72"
    name:
    - unzip
    - php
    - php-fpm
    - php-mbstring
    - php-xml
    - php-pecl-yaml
    - php-json
    - php-zip
    - php-mysqlnd
    - php-opcache
    - php-process
    state: present

- name: Xdebugがインストールされていること
  yum:
    enablerepo: "remi,remi-php72"
    name:
    - php-xdebug
    state: present
  notify: restart_php-fpm
  when: env == 'vagrant'

- name: Xdebug設定ファイルが存在すること
  template:
    src: ../templates/etc/php.d/15-xdebug.ini.j2
    dest: /etc/php.d/15-xdebug.ini
    owner: root
    group: root
    mode: 0664
  notify: restart_php-fpm
  when: env == 'vagrant'

- name: Composerがインストールされていること
  shell: which composer
  register: is_composer_installed
  changed_when: is_composer_installed.rc != 0
  ignore_errors: True

- name: Composerのインストール
  shell: |
    curl -o /tmp/composer-setup.php -L https://getcomposer.org/installer
    php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer
    rm /tmp/composer-setup.php
  when: is_composer_installed.rc != 0

- name: php.iniが存在すること
  template:
    src: ../templates/etc/php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: Opcache用設定ファイルが存在すること
  template:
    src: ../templates/etc/php.d/10-opcache.ini
    dest: /etc/php.d/10-opcache.ini
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php.iniが存在すること
  template:
    src: ../templates/etc/php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php-fpm.confが存在すること
  template:
    src: ../templates/etc/php-fpm.conf.j2
    dest: /etc/php-fpm.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php-fpmのプール設定(デフォルト)は存在しないこと
  file:
    path: /etc/php-fpm.d/www.conf
    state: absent
  notify: reload_php-fpm


- name: php-fpmのプール設定のインストール
  template:
    src: ../templates/etc/php-fpm.d/web.conf.j2
    dest: /etc/php-fpm.d/web.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php-fpmサービスが自動起動すること
  systemd:
    name: php-fpm.service
    enabled: true
    state: started

- name: php-fpmのログディレクトリが書き込み可能で存在すること
  file:
    path: /var/log/php-fpm
    owner: nginx
    group: nginx
    mode: 0755
    state: directory
  notify: reload_php-fpm

- name: エラーログをrootユーザー以外も参照できること
  file:
    path: /var/log/php-fpm/error.log
    owner: root
    group: root
    mode: 0644
    state: touch
  notify: reload_php-fpm

- name: php-fpm用logrotate設定が存在すること
  template:
    src: ../templates/etc/logrotate.d/php-fpm.j2
    dest: /etc/logrotate.d/php-fpm
    owner: root
    group: root
    mode: 0644

- name: "[外部環境用]HTTP用アプリケーションログのlogrotate設定が存在すること"
  template:
    src: ../templates/etc/logrotate.d/laravel.j2
    dest: /etc/logrotate.d/laravel
    owner: root
    group: root
    mode: 0644
  when: env != 'vagrant'

- name: "[外部環境用]CLI用アプリケーションログのlogrotate設定が存在すること"
  template:
    src: ../templates/etc/logrotate.d/laravel-cli.j2
    dest: /etc/logrotate.d/laravel-cli
    owner: root
    group: root
    mode: 0644
  when: env != 'vagrant'
