- name: Remiリポジトリが存在すること
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present


- name: PHPとLaravel関連モジュールがインストールさてていること
  yum:
    enablerepo: "remi,remi-php72"
    name:
    - php
    - php-fpm
    - php-mbstring
    - php-xml
    - php-pecl-yaml
    - php-json
    - php-zip
    - php-mysqlnd
    - php-opcache
    - php-process
    state: present

- name: Xdebugがインストールされていること
  yum:
    enablerepo: "remi,remi-php72"
    name:
    - php-xdebug
    state: present
  when: env == 'development'

- name: Composerがインストールされていること
  shell: which composer
  register: is_composer_installed
  changed_when: is_composer_installed.rc != 0
  ignore_errors: True

- name: Composerのインストール
  shell: |
    curl -o /tmp/composer-setup.php -L https://getcomposer.org/installer
    php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer
    rm /tmp/composer-setup.php
  when: is_composer_installed.rc != 0

- name: php-fpm.confのインストール
  template:
    src: ../templates/php-fpm.conf.j2
    dest: /etc/php-fpm.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php-fpmのプール設定のインストール
  template:
    src: ../templates/php-fpm.d/web.conf.j2
    dest: /etc/php-fpm.d/web.conf
    owner: root
    group: root
    mode: 0664
  notify: reload_php-fpm

- name: php-fpmサービスが自動起動すること
  systemd:
    name: php-fpm.service
    enabled: true
    state: started

- name: .envファイルの設定
  template:
    src: "../templates/.env.{{ env }}"
    dest: "{{ project_root }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664

- name: ストレージフォルダが書き込み可能であること
  file:
    path: "{{ project_root }}/storage"
    state: directory
    recurse: true
    mode: 0777

- name: キャッシュフォルダが書き込み可能であること
  file:
    path: "{{ project_root }}/bootstrap/cache"
    state: directory
    recurse: true
    mode: 0777
  